SELECT 
    CAMPANYA.NOMBRE 
    , CAMPANYA.IDCAMPANYA
    , USUARIO.NAME
    , USUARIO.IDUSUARIO
    , USUARIO.LOGIN
    , COUNT(TRANSACCION.IDTRANSACCION) AS Totals
    , SUM(
        CASE 
            WHEN (TRANSACCION.tFinal - TRANSACCION.tInicio) >= CAMPANYA.TINICIAL 
            AND (TRANSACCION.tFinal - TRANSACCION.tInicio) <= CAMPANYA.TFINAL 
            THEN 1 
            ELSE 0 
        END
    ) AS 'Total Transactions Between tInicio and tFinal'
FROM TRANSACCION 
INNER JOIN USUARIO ON USUARIO.IDUSUARIO = TRANSACCION.idAgente 
INNER JOIN CAMPANYA ON CAMPANYA.IDCAMPANYA = TRANSACCION.idCampanya 
GROUP BY 
    CAMPANYA.NOMBRE,
    CAMPANYA.IDCAMPANYA,
    USUARIO.NAME,
    USUARIO.IDUSUARIO,
    USUARIO.LOGIN;